---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: miso-gallery
  namespace: flux-system
spec:
  interval: h1
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
